[workspace]
name = "napari-devbiot"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]

[dependencies]
python = "3.9.*"
devbio-napari = "*"
napari = "0.4.19"
pyqt = "*"

pyclesperanto = "*"
pip = "*"

[pypi-dependencies]
napari-clusters-plotter = "==0.8.1"

