[workspace]
name = "napari-devbiot"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
download-data = "curl -L https://zenodo.org/records/17986091/files/Lund.tif --output data/Lund.tif --create-dirs"

[dependencies]
python = "3.9.*"
devbio-napari = "*"
napari = "0.4.19"
pyqt = "*"

pyclesperanto = "*"
pip = "*"

[pypi-dependencies]
napari-clusters-plotter = "==0.8.1"

